name: Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  NAME: "Musk"
  
jobs:
  build:
    env:
      JAVA_VER: "21"
      DIST: "temurin"
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ env.JAVA_VER }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VER }}
        distribution: ${{ env.DIST }}
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean package

    - name: Print name
      run: echo "The build name is $NAME | Java is $JAVA_VER | Build is $BUILD | os is $RUNNER_OS | API key is ${{ secrets.API_KEY }}"
      env:
        BUILD: "v2.0"
