name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  NAME: "Musk"
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VER: "21"
      DIST: "temurin"

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ env.JAVA_VER }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VER }}
        distribution: ${{ env.DIST }}
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Print name
      run: echo "The build name is $NAME | Java is $JAVA_VER | Distribution is $DIST | os is $RUNNER_OS"
